# Generated by Django 4.1.1 on 2023-01-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='treinador',
        ),
        migrations.AlterField(
            model_name='atleta',
            name='posicao_jogo',
            field=models.PositiveIntegerField(),
        ),
    ]
