# Generated by Django 4.1.1 on 2023-01-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_atleta_treinador_alter_atleta_posicao_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='posicao_jogo',
            field=models.CharField(max_length=50),
        ),
    ]
