# Generated by Django 4.1.1 on 2023-02-24 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_questionariotacsi_atleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='atleta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.atleta'),
        ),
    ]
