# Generated by Django 4.1.1 on 2023-02-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_questionarioinfopaissocieconomico_altura_mae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='escolaridade_pessoa_referencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
