# Generated by Django 4.1.1 on 2023-02-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_avaliacaoantropometricafisicomotora_agilidade_t1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoantropometricafisicomotora',
            name='atleta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.atleta'),
        ),
        migrations.AlterField(
            model_name='avaliacaoantropometricafisicomotora',
            name='treinador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.treinador'),
        ),
    ]
