# Generated by Django 4.1.1 on 2023-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_avaliacaoantropometricafisicomotora_atleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoaerobica',
            name='estagio',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoaerobica',
            name='volta',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
