# Generated by Django 4.1.1 on 2023-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_avaliacaoaerobica_treinador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionariodadospessoais',
            name='quantas_lesoas',
        ),
        migrations.AddField(
            model_name='questionariodadospessoais',
            name='quantas_lesoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='duracao_treino_horas1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='duracao_treino_horas2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='esporte_preferido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='frequencia_semanal_treino1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='frequencia_semanal_treino2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='idade_inicio_futebol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='instituicao_treinamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='maior_nivel_competicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='maior_nivel_vitoria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='modalidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='nome_competicao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='nome_competicao_maior_vitoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='participa_competicao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='qual_esporte_treina1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='qual_esporte_treina2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='quer_ser_atleta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='tem_orientacao_treinador',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='tempo_treinamento1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='tempo_treinamento2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='teve_lesao',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
