# Generated by Django 4.2.1 on 2023-05-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_atleta_algum_problema_saude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoantropometricafisicomotora',
            name='atleta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='av_antropometrica_fisicomotora', to='api.atleta'),
        ),
    ]
