# Generated by Django 4.2.1 on 2023-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_avaliacaoantropometricafisicomotora_agilidade_t1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoantropometricafisicomotora',
            name='idade_pvc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoantropometricafisicomotora',
            name='maturacao_biologica',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoantropometricafisicomotora',
            name='motivacao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
