# Generated by Django 4.2.1 on 2023-06-07 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_avaliacaopotencialesportivo_atleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaopotencialesportivo',
            name='atleta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='av_potencial_esportivo', to='api.atleta'),
        ),
        migrations.AlterField(
            model_name='avaliacaopotencialesportivo',
            name='intangivel_potencial_esportivo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaopotencialesportivo',
            name='potencial_futuro',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
