# Generated by Django 4.2.1 on 2023-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_avaliacaoantropometricafisicomotora_habilidades_psicologicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaopotencialesportivo',
            name='intangivel_potencial_esportivo',
        ),
        migrations.AddField(
            model_name='avaliacaoantropometricafisicomotora',
            name='intangivel_potencial_esportivo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
