# Generated by Django 4.1.1 on 2023-02-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_atleta_posicao_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionariosoq',
            name='atleta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.atleta'),
        ),
    ]
