# Generated by Django 4.1.1 on 2023-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_questionarioinfopaissocieconomico_atleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='altura_mae',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='altura_pai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarioinfopaissocieconomico',
            name='questao9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
