# Generated by Django 4.1.1 on 2023-02-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_questionarioinfopaissocieconomico_escolaridade_pessoa_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='atleta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.atleta'),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='desempenho_comparativo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='desempenho_percebido',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='modalidade',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='pais_praticantes_esporte',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao10',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao4',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao5',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao6',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao7',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao8',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='questao9',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='tem_atleta_na_familia',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
