# Generated by Django 4.1.1 on 2023-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_avaliacaoaerobica_estagio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoaerobica',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
