# Generated by Django 4.1.1 on 2023-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_questionariodadospessoais_quantas_lesoas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionariodadospessoais',
            name='maior_nivel_vitoria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
