# Generated by Django 4.2.1 on 2023-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_questionarioacsi_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='algum_problema_saude',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='categoria_etaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='contato',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='dominancia_maos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='dominancia_pes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='idade_menarca',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='instituicao_clube',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instituição/Clube'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='ja_teve_menarca',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='posicao_jogo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='possui_deficiencia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='qual_deficiencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='qual_medicamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='qualidade_sono',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='recuperacao_ao_acordar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='repetente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='senha',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='sexo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='tipo_escola',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='usa_medicamento_regularmente',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
