# Generated by Django 4.2.1 on 2023-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_avaliacaoantropometricafisicomotora_atleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoantropometricafisicomotora',
            name='habilidades_psicologicas',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoantropometricafisicomotora',
            name='habilidades_taticas',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoantropometricafisicomotora',
            name='resistencia',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoantropometricafisicomotora',
            name='suporte_familiar',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
