# Generated by Django 4.2.1 on 2023-05-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_avaliacaoantropometricafisicomotora_idade_pvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoantropometricafisicomotora',
            name='idade_pvc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
