# Generated by Django 4.2.1 on 2023-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_avaliacaoantropometricafisicomotora_idade_pvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaopotencialesportivo',
            name='intangivel_potencial_esportivo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
