# Generated by Django 4.2.1 on 2023-07-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_avaliacaopotencialesportivo_intangivel_potencial_esportivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaoantropometricafisicomotora',
            name='habilidades_psicologicas',
        ),
        migrations.RemoveField(
            model_name='avaliacaoantropometricafisicomotora',
            name='habilidades_taticas',
        ),
        migrations.RemoveField(
            model_name='avaliacaoantropometricafisicomotora',
            name='idade_pvc',
        ),
        migrations.RemoveField(
            model_name='avaliacaoantropometricafisicomotora',
            name='intangivel_potencial_esportivo',
        ),
        migrations.RemoveField(
            model_name='avaliacaoantropometricafisicomotora',
            name='maturacao_biologica',
        ),
        migrations.RemoveField(
            model_name='avaliacaoantropometricafisicomotora',
            name='motivacao',
        ),
        migrations.RemoveField(
            model_name='avaliacaoantropometricafisicomotora',
            name='resistencia',
        ),
        migrations.RemoveField(
            model_name='avaliacaoantropometricafisicomotora',
            name='suporte_familiar',
        ),
    ]
