# Generated by Django 4.2.1 on 2023-07-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_avaliacaoantropometricafisicomotora_habilidades_psicologicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='pais_praticantes_esporte',
        ),
        migrations.RemoveField(
            model_name='questionariocomppercebidasuportefamiliar',
            name='tem_atleta_na_familia',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='escolaridade_pessoa_referencia',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao1',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao10',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao11',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao12',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao13',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao14',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao2',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao3',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao4',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao5',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao6',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao7',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao8',
        ),
        migrations.RemoveField(
            model_name='questionarioinfopaissocieconomico',
            name='questao9',
        ),
        migrations.AddField(
            model_name='questionarioinfopaissocieconomico',
            name='modalidade',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questionarioinfopaissocieconomico',
            name='pais_praticantes_esporte',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='questionarioinfopaissocieconomico',
            name='tem_atleta_na_familia',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
